#!/usr/bin/env bash
#

counter=0


while [ $counter -le 100 ]
	do
	((counter++))
	if ! ((counter%3)) && ! ((counter%5))
	then
		echo FizzBuzz
	elif ! ((counter%3))
	then
	echo Fizz
	elif ! ((counter%5))
	then
		echo Buzz
	else
		echo $counter
	fi
done
		
