#!/usr/bin/env bash
# display 10 times Best School except fot the 9th iteration it display "hi"

counter=1
while [ $counter -le 10 ]
do 	
	if [ $counter -eq 9 ]
	then
	echo "Hi"
	else
	echo "Best School"
fi
	((counter++))
done
