#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:

#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

counter=1

while [ $counter -le 20 ]
do 
	case $counter in

	4)
	printf  "$counter\nbad luck for China\n"
	;;

	9)
	printf  "$counter\nbad luck from Japan\n"
	;;

	17)
	printf  "$counter\nbad luck from Italy\n"
	;;

	*)
	echo $counter
	;;
esac
	((counter++))
done
