#!/usr/bin/env bash
#



	if [ "$1" == "start" ]
	then
		sudo ./manage_my_process&
		echo $$ > /tmp/my_process.pid
		echo manage_my_process started
	elif [ "$1" == "stop" ]
	then	
		pkill -f "bash ./manage_my_process"
		echo "manage_my_process sopped"
	elif [ "$1" == "restart" ]
	then
                pkill -f "bash ./manage_my_process"
		sudo rm /tmp/my_process.pid
		sudo ./manage_my_process&
		echo $$ > /tmp/my_process.pid
		echo manage_my_process restarted
	else
	echo "Usage: manage_my_process {start|stop|restart}"
	fi


